
final Map<String, Set<String>> cats = {
  'Всі': {},
  'Авто': {'MaksPodzigun', 'autogeek', },
  'Благоустрій': {'chaplinskyvlog', 'dostupno2020', 'stop_goose', },
  'Військове': {'Lykhovii', 'milinua', 'informnapalm', 'AngryUA'},
  'Гумор': {'torontotv', 'kolegistudio', 'dostupno2020', 'dovkolabotanika', 'ninaukraine', 'verumT', 'uareview', 'pereozvuchka_ua'},
  'Дизайн': {'telegrafdesign', },
  'Дітям': {'user?u=28899940', 'learningtogetherua', 'KhmarynkaUA', 'oum_spadshchyna', 'PaniVchytelka', 'pershosvit', },
  'Допомога': {'prytula', 'savelife_in_ua', 'uanimals', 'rsukraine_org_ua', 'serhiyzhadan', 'donorua', 'dostupno2020', 'heroyika', },
  'Екологія': {'NowasteUkraine', },
  'Ігри': {'PlayUA', 'mariamblog', 'vertigoUA', 'pad0n', 'rendarosua', 'gamer_fm', 'gamestreetua', 'PSUkraine', 'oldboiua', 'WBG', 'teoriyagry', },
  'Інвестиції': {'familybudgetcomua'},
  'Історія': {'imtgsh', 'historyUA', 'kozak_media', 'kgbfiles', },
  'Кіно': {'Geek_Journal', 'mariamblog', 'vertigoUA', 'pankarpan', 'zagin', 'animeK', 'mangua', 'asambleyA', 'miketvua', 'Salertino', },
  'Книги': {'annika_blog', 'vyshnevyjcvit', 'mariamblog', 'vertigoUA', 'knyzhkova_dylerka', 'GulbanuBibicheva', 'svitlana', 'robmenus', 'TheAsya', 'enma_and_books', 'kliusmarichka', 'liubovgoknyg', 'mangua', 'asambleyA', 'paralel3', 'kultpodcast', 'diasporiana', },
  'Культура': {'undergroundhumanities', 'vmistozher', 'raguli', },
  'Музей': {'odesafineartsmuseum'},
  'Музика': {'UkrainianLiveClassic', 'zhadanisobaki', 'liroom', 'mefreel', 'slukh', 'uaestrada', 'ukrainedancing'},
  'Наука': {'CikavaNauka', 'rationalist', 'dovkolabotanika', 'pityatko', 'VorobieiBohdan', 'vsesvit_ua', 'naukaua', 'vsesvitua', },
  'Подорожі': {'ukrainer', 'user?u=44661751', 'lowcostua', 'nebolviv'},
  'Політика': {'skrypinua', 'sternenko', 'vatashow', 'bihusinfo', 'raguli', 'torontotv', 'ukrainianweek', 'textyorgua', 'Bykvu', 'informnapalm', 'slidstvo_info', 'portnikov', 'nestorvolya', 'valerii'},
  'Природа': {'propohody', 'user?u=44661751', },
  'Радіо': {'radioaristocrats', 'radioskovoroda', 'Hromadske_Radio', },
  'Творчість': {'user?u=16774315', 'uacomix', 'nicopogarskiy', 'prihodnik', 'Shablyk', 'bez_mezh_studios', 'sbt_localization', 'AdrianZP', 'gwean_maslinka', 'mariamblog', 'strugachka', 'cikavaideya', 'TheAsya', 'user?u=10599103', 'bbproject', 'fvua', 'JBPetersonUkraine'},
  'Театр': {'les_kurbas_theatre', },
  'Texнології': {'tokar', 'viewua', 'itpassions', 'jarvis_net_ua', 'nonamepodcast', 'Pingvins', 'manifestplatform', 'naukaua', },
  'Різне': {'shitiknowlive', 'itworksonmypc', 'radioskorbota', 'lustrum', 'manifestplatform', 'balytska', 'kinshov', 'rist_center', 'inforules', 'behindthenews', 'iyura', 'musetang', 'radiopodil', 'need_science', },
  'Иншомовні': {'thealphacentauri', 'yanina', 'sershenzaritskaya', 'faideyren', 'bellatrixaiden', 'mukha', 'tanyacroft', 'allyourhtml'},
};