final Map<String, String> data_about = {
  '23daphnia': 'читає гарні книги',
  '5HT': 'створює N2O',
  'AdrianZP': 'створює Ukrainian dubbing, education & other video',
  'aiesechouseua': 'створює AIESEC House UA',
  'allyourhtml': 'створює frontend videos',
  'amanogawa': 'створює анімешний контент українською',
  'AngryUA': 'створює контент в підтримку Української Армії',
  'animeK': 'створює відео',
  'anitubeinua': 'створює subtitles, dubbing',
  'AniUA': 'створює series dub and translaitioins',
  'annika_blog': 'створює youtube videos',
  'asambleyA': 'створює youtube videos',
  'ATR_UA': 'створює актуальные новости в украинском обществе и жизни крымских татар',
  'autogeek': 'створює цікавинки зі світу електромобілів в Україні та світі',
  'balytska': 'створює lifestyle video in Ukrainian',
  'bazilikmedia': 'створює media about communications, advertising and brands ',
  'bbproject': 'створює music video, covers, instrumental folk music',
  'beautyandgloom': 'створює огляди книжок та коміксів',
  'behindthenews': 'створює  тексти, у яких спростовуємо фейки, розвінчуємо міфи',
  'belkininovak': 'висвічуємо яскраві події світового шоу Реслінгу WWE',
  'bellatrixaiden': 'створює cosplay',
  'berehtyIF': 'створює громади, які бережуть архітектурну спадщину',
  'besahy': 'створює відео рецепти з українським присмаком',
  'bez_mezh_studios': 'створює metal music content',
  'bihusinfo': 'викриває поганців та їхні схеми/anti-corruption investigations',
  'BlogerFM': 'створює онлайн радіо, інтерв’ю та інші круті штуки',
  'blogmayster': 'створює videos',
  'Bykvu': 'інформує про важливі події в Україні та світі',
  'chaplinskyvlog': 'створює vlog about architecture, urbanism and city life',
  'ChasIstoriy': 'створює storytelling platform',
  'chtyvo': 'створює схрон україномовної літератури',
  'chytomo': 'створює матеріали про культуру читання і мистецтво книговидання',
  'cikavaideya': 'створює переклад та озвучення серіалів і фільмів',
  'CikavaNauka': 'популяризує науку українською',
  'comixua': 'створює мальовані історії',
  'costua': 'робимо з українців свідомих платників податків',
  'cukr': 'створює новини та історії міста Суми',
  'dailymetal_radiogarta': 'створює Ukrainian underground info space for metal music',
  'deadlinetalkshow': 'створює розмови про медіа наживо',
  'diasporiana': 'створює writing/journalism and cool stuff',
  'Did_Oles_Falcon_UA': 'створює videos and communities',
  'DITHOM': 'створює videos',
  'diypodcast': 'створює історії, де підприємці діляться досвідом запуску власної справи',
  'docult': 'створює відео про українську та всесвітню історію',
  'donorua': 'створює digital platform for quick blood donor search',
  'dostupno2020': 'створює video',
  'dovkolabotanika': 'створює scientific memes, popular science video and textes',
  'dustanciyka': 'створює освітні відео',
  'dvokolisni_hroniky': 'створює travel videos',
  'eileena': 'створює covers and translations of songs',
  'enjoythescience': 'створює education content for Ukrainians',
  'enma_and_books': 'створює відеорецензії та огляди книг',
  'faideyren': 'створює cosplay',
  'familybudgetcomua': 'допомагає українцям приймати розумні фінансові рішення',
  'fazugenealogy': 'створює videos and local business',
  'findwayua': 'створює базу цікавих місць України та розвиває туризм',
  'fromfaraway': 'створює podcasts',
  'fvua': 'озвучує аніме та мульсеріали українською',
  'gamer_fm': 'створює відео та прямі трансляції українською мовою',
  'gamestreetua': 'створює ігровий портал',
  'Geek_Informator': 'створює news and reviews (videogames, movies, technologies, comics)',
  'Geek_Journal': 'створює youtube videos',
  'GulbanuBibicheva': 'створює videos',
  'gwean_maslinka': 'створює озвучення аніме українською',
  'happypaw': 'створює videos',
  'heroyika': 'створює building monuments and memorials to the defenders of Ukraine',
  'historyUA': 'створює відео про історію України та світу',
  'historywall': 'створює videos',
  'horobyna': 'створює videos',
  'hotperevod': 'створює свіжий український контент, ми тут аби ви сміялися',
  'Hromadske_Radio': 'створює вдумлива розмова у прямому ефірі та подкастах',
  'imtgsh': 'створює відео для ютуб канала імені Т.Г. Шевченка',
  'informnapalm': 'створює content of public importance',
  'inforules': 'створює відео про те як споживати інформацію безпечно',
  'inshe': 'створює подкасти',
  'islndtv': 'створює журналістські розслідування, інтелектуальний контент, інтерв\'ю',
  'itguildukraine': 'створює легітимне, незалежне та демократичне професійне об\'єднання',
  'itpassions': 'створює інтерв\'ю з IT-спеціалістами',
  'itworksonmypc': 'створює vlog',
  'iyura': 'створює   подкаст про мейкерів та відкриті майстерні',
  'jarvis_net_ua': 'створює Джарвіс, WRating, ТиДиви, ТиДивиДіти',
  'JBPetersonUkraine': 'створює переклади професора Джордана Пітерсона українською',
  'kartofanchyk': 'створює розповідаю про технології на прикладі процесу садіння картоплі',
  'kgbfiles': 'створює розсекречені документи з архіву СБУ',
  'KhmarynkaUA': 'створює український контент для дітей і дорослих',
  'kliusmarichka': 'створює відео контент на книжкову тематику українською мовою',
  'knyzhkova_dylerka': 'створює відео про книги',
  'kolegistudio': 'створює відео контент, що має сенс',
  'konotopcity': 'створює контент',
  'kozak_media': 'створює ютюб канал присвячений прикладній історії України',
  'krutoznavstvo': 'створює просвітницький клуб крутознавців',
  'kultpodcast': 'створює podcasts',
  'kuznetsovalife': 'створює слова і речення',
  'Lakuna': 'створює sci-pop videos',
  'lee_online': 'створює movies and tv shows',
  'les_kurbas_theatre': 'створює ukrainian intellectual theater',
  'letslearnukrainian': 'створює videos on ukrainian grammar and vocabulary',
  'liganet': 'створює writing/journalism',
  'liroom': 'створює медіа про нову українську музику',
  'liubovgoknyg': 'створює відео про книги, серіали та фільми',
  'lowcostua': 'створює writing/journalism and communities',
  'loyer': 'створює місце, де ви можете зізнатися нам у почуттях',
  'lustrum': 'створює writing/journalism',
  'LvivNationalPhilharmonic': 'створює music',
  'Lykhovii': 'створює online web-site',
  'lyukmedia': 'створює історії, спільноту, сенси',
  'MaksPodzigun': 'створює F1Podcast patreon club',
  'mangua': 'створює podcast series about manga and anime in Ukraine',
  'manifestplatform': 'створює videos',
  'mariamblog': 'створює video reviews, Ukrainian dubbing video',
  'mefreel': 'створює music',
  'merezhyvo': 'зберігає та популяризує дерев\'яну архітектуру Чернігівщини',
  'miketvua': 'створює україномовний контент на ютюб',
  'milinua': 'створює мілітарний портал',
  'mokrec': 'створює journalism',
  'mukha': 'створює cosplay and photography',
  'musetang': 'створює гітарні кавери та розбори українською',
  'nareshticlub': 'створює простір для спілкування українською',
  'naukaua': 'створює новини науки українською',
  'nebolviv': 'створює відео про цікаві місця Галичини, України і не тільки',
  'need_science': 'створює науково-популярний контент українською',
  'neformat': 'створює journalism/articles about Ukraine underground music',
  'nestorvolya': 'створює український незалежний блогер, громадська ініціатива інфоВАРТА',
  'nicopogarskiy': 'створює papercraft 2D miniatures',
  'ninaukraine': 'створює fun, inspiring and educational videos',
  'nonamepodcast': 'створює український подкаст про кібербезпеку',
  'NowasteUkraine': 'створює public sorting spaces ',
  'obrazpublicua': 'створює better worlds',
  'odesafineartsmuseum': 'створює сучасний український музей',
  'office_transformation': 'створює video and podcast',
  'oldboiua': 'створює відео та стріми про ігри та ігрову індустрію українською',
  'oleksandr_ant': 'створює books and articles about economics, including economic news',
  'olesyabobruyko': 'створює відео про психічне здоров\'я і щастя',
  'omtvua': 'створює україномовний контент на важливі соціально-політичні теми',
  'otvinta': 'створює music and shows for you',
  'oum_spadshchyna': 'створює патріотичне середовище для свідомих та дієвих молодих українців',
  'pad0n': 'створює україномовний вміст: озвучування, ігрові відео, подкасти та стріми',
  'palindrom': 'створює music, video, lyrics',
  'PaniVchytelka': 'створює освітній контент',
  'pankarpan': 'створює україномвоний канал присвячений кіно та поп-культурі',
  'paralel3': 'створює youtube videos and podcast Баляндраси',
  'pereozvuchka_ua': 'створює смішні озвучування українською',
  'pershosvit': 'створює розважально-освітній анімаційний ютюб канал для дітей',
  'Pingvins': 'створює огляди, статті, відео, бази даних, системи оцінювання пристроїв',
  'pityatko': 'створює навколопсихологічні науково-популярні відео ',
  'pivpodcast': 'створює українськомовні подкасти про музику',
  'PlayUA': 'створює media content',
  'portnikov': 'створює article, video, blogs',
  'ppidcast': 'створює кльові подкасти',
  'prihodnik': 'створює Dungeons & Dragons українською: переклади, мапи, ілюстрації тощо',
  'propohody': 'створює найкрутіший проєкт про гори, мандри і спорядження, українською',
  'prytula': 'створює videos',
  'PSUkraine': 'створює спільноту "Play State Ukraine"',
  'radioaristocrats': 'створює podcasts and videos',
  'radiopodil': 'створює першу незалежну спільноту українськомовних подкастів',
  'radioskorbota': 'створює подкасти',
  'radioskovoroda': 'створює writing/journalism and podcasts',
  'raguli': 'досліджує хиби нашого соціуму й українського медіапростору',
  'rationalist': 'створює україномовний контент наукової тематики',
  'razvelibardak': 'створює чисте та комфортне місто',
  'rendarosua': 'створює videos about videogames and geek stuff in Ukrainian',
  'rist_center': 'створює україномовний навчальний контент для креативної та ІТ-індустрії',
  'robmenus': 'створює відео огляди (книжки, фільми, часом ігри) і подкасти',
  'RockRadioUA': 'створює online радіо',
  'rsukraine_org_ua': 'допомагає відновити здоров\'я захисникам України',
  'rudnyi': 'створює tutorials, education videos',
  'Salertino': 'створює контент українською про кіно і близько цієї теми',
  'savelife_in_ua': 'створює posts and videos about Ukrainian veteran\'s rehabilitation',
  'sbt_localization': 'створює translations',
  'serhiyzhadan': 'створює writing/journalism and music',
  'sershenzaritskaya': 'створює rock and metal covers ',
  'Shablyk': 'створює video',
  'shitiknowlive': 'створює ваш любимий український подкаст',
  'shobsho': 'створює humor, politics, gonzo journalism',
  'skrypinua': 'створює YouTube-channels',
  'slidstvo_info': 'створює журналістські розслідування',
  'slukh': 'створює онлайн-медіа про музику та все, що навколо неї',
  'soblya': 'створює королі подкастингу України, принаймні Львівської області',
  'sternenko': 'створює YouTube-channel',
  'StopTheMoose': 'створює зміни в свідомості українських громадян',
  'strugachka': 'створює videos and cool stuff',
  'svidomi': 'створює актуальні новини та суспільний медіа-контент',
  'svitlana': 'створює YouTube videos',
  'svitlotin': 'створює україномовні відео на історичну тематику',
  'TA_studio': 'створює наче гумор, ну ми сміємось',
  'tanyacroft': 'створює cosplay content',
  'tatotake': 'створює videos and writing/journalism',
  'tatysho': 'створює подкаст',
  'Tayemna_kimnata': 'створює відео та трансляції про відеоігри',
  'taytake': 'створює videos and podcasts',
  'techtoloka': 'створює communities',
  'telegrafdesign': 'створює writing/journalism',
  'teoriyagry': 'створює текстові та відеоогляди на настільні ігри та дотичні теми',
  'textyorgua': 'створює журналістика даних / data journalism',
  'thealphacentauri': 'створює videos',
  'TheAsya': 'створює audiobooks and gameplays voiceover translations to Ukrainian',
  'tokar': 'створює відео про цифрову безпеку, космос і технології',
  'torontotv': 'створює гумористичні, соціально-політичні, культурні та не дуже відео',
  'totem_publisher': 'створює чарівні історії',
  'UA_direct_democracy': 'створює демократію без посередників',
  'uacomix': 'створює comics publishing house',
  'uaestrada': 'створює українська музика 50-х–80-х років',
  'uagenealogy': 'створює genealogical content',
  'uanimals': 'створює гуманістичний рух за права тварин ',
  'uareview': 'створює сатиричні новини українською',
  'ubmdr': 'створює pool of stem cells donors in Ukraine',
  'ukrainedancing': 'створює подкасти/ музику українською мовою',
  'ukrainer': 'створює videos and journalism',
  'UkrainianLiveClassic': 'створює 1st mobile app with classical music of Ukraine',
  'ukrainianweek': 'створюємо якісний контент для нашої аудиторії',
  'ukrmod': 'створює stories about modern architecture and monumental art of Ukraine',
  'undergroundhumanities': 'створює освітні відео про мову, літературу та культуру',
  'user?u=16774315': 'створює graphic designer and illustrator',
  'user?u=28899940': 'створює fiction for children',
  'user?u=44661751': 'створює відео про справжню Україну',
  'user?u=50286152': 'створює podcast',
  'valerii': 'створює videos and writing',
  'vatashow': 'створює палаюча вата',
  'vatatv': 'створює Vata TV',
  'vertigoUA': 'створює media',
  'verumT': 'створює відоси',
  'vidminniotsinky': 'створює українська мова та література',
  'viewua': 'створює IT-гаджети',
  'vlad_storyteller': 'створює освітні відео українською мовою про написання історій',
  'vmistozher': 'створює подкаст вмістожер',
  'volyasovich': 'створює videos',
  'volynonline': 'створює інтернет-видання (mas media)',
  'VorobieiBohdan': 'створює огляди зоряного неба та астрономічних подій',
  'vovazilvova': 'створює пісні, музичні відео і контент, що надихає, тішить і бадьорить',
  'vrajennya': 'створює communities and podcasts',
  'vsesvit_ua': 'створює відео про космос українською',
  'vsesvitua': 'розповідає про космос просто',
  'vyshnevyjcvit': 'створює videos about books',
  'WBG': 'створює board game videos, відео про настільні ігри українською',
  'wild_theatre': 'створює український незалежний театр',
  'wildfoxfilm': 'створює про історію та життя в минулому: весело, просто, з пивом',
  'wszystko_band': 'створює  Ukrainian music, music videos',
  'yanina': 'створює movies and YouTube shows',
  'zagin': 'створює огляди на українське кіно',
  'zasnovnyky': 'створює подкаст про українських змінотворців, які творять сьогодення',
  'zhadanisobaki': 'створює music',
  'zhyteli_kyieva': 'створює storytelling, photography, journalism ',
  'zvedeno': 'створює news',
};
