final Map<String, Set<String>> cats = {
  'Найпопулярніші': {},
  'Архітектура': {'chaplinskyvlog', 'merezhyvo', 'ukrmod'},
  'Військове': {'informnapalm', 'Lykhovii', 'milinua'},
  'Гумор': {'AniUA', 'dovkolabotanika', 'horobyna', 'hotperevod', 'kartofanchyk', 'ninaukraine', 'pereozvuchka_ua', 'shobsho', 'TA_studio', 'taytake', 'torontotv', 'uareview', 'verumT'},
  'Дітям': {'KhmarynkaUA', 'oum_spadshchyna', 'PaniVchytelka', 'pershosvit', 'user?u=28899940'},
  'Допомога': {'donorua', 'dostupno2020', 'prytula', 'rsukraine_org_ua', 'serhiyzhadan', 'uanimals', 'ubmdr'},
  'Ігри': {'DITHOM', 'gamestreetua', 'Geek_Informator', 'oldboiua', 'pad0n', 'PSUkraine', 'rendarosua', 'Tayemna_kimnata', 'teoriyagry', 'TheAsya', 'vertigoUA', 'WBG'},
  'Історія': {'historyUA', 'historywall', 'imtgsh', 'kgbfiles', 'kozak_media', 'svitlotin', 'wildfoxfilm'},
  'Кіно': {'animeK', 'asambleyA', 'Geek_Informator', 'Geek_Journal', 'mangua', 'mariamblog', 'miketvua', 'pankarpan', 'Salertino', 'takflix', 'vertigoUA', 'zagin'},
  'Культура': {'les_kurbas_theatre', 'raguli', 'undergroundhumanities', 'vmistozher'},
  'Література': {'23daphnia', 'asambleyA', 'chtyvo', 'chytomo', 'diasporiana', 'dolliteraturne', 'enma_and_books', 'GulbanuBibicheva', 'kliusmarichka', 'knyzhkova_dylerka', 'ksenia_kellerman', 'kultpodcast', 'kuznetsovalife', 'mangua', 'mariamblog', 'Ole_Sia', 'readingmary', 'svitlana', 'TheAsya', 'vertigoUA', 'vrajennya', 'vyshnevyjcvit', 'user?u=76475135', 'user?u=83097324', 'yanareadwithme'},
  'Містознавство': {'chaplinskyvlog', 'office_transformation', 'StopTheMoose'},
  'Музика': {'bbproject', 'eileena', 'fromfaraway', 'liroom', 'LvivNationalPhilharmonic', 'mefreel', 'musetang', 'otvinta', 'palindrom', 'pivpodcast', 'slukh', 'uaestrada', 'ukrainedancing', 'UkrainianLiveClassic', 'vovazilvova', 'wszystko_band', 'zhadanisobaki'},
  'Навчання': {'blogmayster', 'dustanciyka', 'inforules', 'nareshticlub', 'need_science'},
  'Наука': {'CikavaNauka', 'dovkolabotanika', 'enjoythescience', 'fazugenealogy', 'naukaua', 'pityatko', 'rationalist', 'uagenealogy', 'VorobieiBohdan', 'vsesvit_ua'},
  'Переклад': {'amanogawa', 'anitubeinua', 'cikavaideya', 'fvua', 'gwean_maslinka', 'JBPetersonUkraine', 'sbt_localization', 'strugachka'},
  'Подорожі': {'dvokolisni_hroniky', 'findwayua', 'lowcostua', 'nebolviv', 'ukrainer', 'user?u=44661751'},
  'Політика': {'bihusinfo', 'Bykvu', 'EuropeanPravda', 'informnapalm', 'islndtv', 'mokrec', 'nestorvolya', 'omtvua', 'portnikov', 'raguli', 'skrypinua', 'slidstvo_info', 'svidomi', 'textyorgua', 'torontotv', 'UA_direct_democracy', 'ukrainianweek', 'valerii', 'vatashow', 'zvedeno'},
  'Природа': {'propohody', 'user?u=44661751'},
  'Професійне': {'bazilikmedia', 'itguildukraine', 'loyer', 'oleksandr_ant', 'olesyabobruyko', 'rist_center', 'user?u=50286152'},
  'Радіо': {'BlogerFM', 'Hromadske_Radio', 'radioaristocrats', 'radioskovoroda', 'RockRadioUA'},
  'Спорт': {'belkininovak', 'MaksPodzigun', 'tatotake'},
  'Творчість': {'AdrianZP', 'nicopogarskiy', 'prihodnik', 'stasmusicmaker', 'uacomix', 'user?u=16774315'},
  'Texнології': {'itpassions', 'jarvis_net_ua', 'manifestplatform', 'naukaua', 'nonamepodcast', 'tokar'},
  'Фінанси': {'costua', 'diypodcast', 'familybudgetcomua', 'vovkst'},
  'Різне': {'ATR_UA', 'autogeek', 'balytska', 'behindthenews', 'besahy', 'itworksonmypc', 'iyura', 'krutoznavstvo', 'liganet', 'lustrum', 'manifestplatform', 'NowasteUkraine', 'odesafineartsmuseum', 'obrazpublicua', 'ppidcast', 'radiopodil', 'radioskorbota', 'shitiknowlive', 'soblya', 'tatysho', 'techtoloka', 'totem_publisher', 'zasnovnyky'},
  'Регіональне': {'berehtyIF', 'cukr', 'konotopcity', 'volynonline', 'zhyteli_kyieva'},
  'Иншомовні': {'5HT', 'allyourhtml', 'bellatrixaiden', 'Did_Oles_Falcon_UA', 'faideyren', 'happypaw', 'letslearnukrainian', 'mukha', 'rudnyi', 'sershenzaritskaya', 'tanyacroft', 'thealphacentauri', 'vatatv', 'vidminniotsinky', 'yanina'},
};
