import 'creator.dart';

final Map<String, Creator> data = {
  '23daphnia': Creator(account: '23daphnia', patrons: null, earnings: Earnings(currency: '\$', value: 7)),
  '5HT': Creator(account: '5HT', patrons: 6, earnings: Earnings(currency: '\$', value: 39)),
  'AdrianZP': Creator(account: 'AdrianZP', patrons: null, earnings: Earnings(currency: '\$', value: 281)),
  'allyourhtml': Creator(account: 'allyourhtml', patrons: 176, earnings: Earnings(currency: '\$', value: 320)),
  'amanogawa': Creator(account: 'amanogawa', patrons: 21, earnings: Earnings(currency: '\$', value: 184)),
  'animeK': Creator(account: 'animeK', patrons: null, earnings: Earnings(currency: '\$', value: 1)),
  'anitubeinua': Creator(account: 'anitubeinua', patrons: null, earnings: null),
  'AniUA': Creator(account: 'AniUA', patrons: null, earnings: Earnings(currency: '\$', value: 2)),
  'asambleyA': Creator(account: 'asambleyA', patrons: null, earnings: null),
  'ATR_UA': Creator(account: 'ATR_UA', patrons: 88, earnings: Earnings(currency: '\$', value: 661)),
  'autogeek': Creator(account: 'autogeek', patrons: null, earnings: null),
  'balytska': Creator(account: 'balytska', patrons: 15, earnings: Earnings(currency: '\$', value: 50)),
  'bazilikmedia': Creator(account: 'bazilikmedia', patrons: null, earnings: null),
  'bbproject': Creator(account: 'bbproject', patrons: 77, earnings: null),
  'behindthenews': Creator(account: 'behindthenews', patrons: 15, earnings: Earnings(currency: '\$', value: 35)),
  'belkininovak': Creator(account: 'belkininovak', patrons: 27, earnings: Earnings(currency: '\$', value: 35)),
  'bellatrixaiden': Creator(account: 'bellatrixaiden', patrons: 7, earnings: Earnings(currency: '\$', value: 23)),
  'berehtyIF': Creator(account: 'berehtyIF', patrons: 10, earnings: Earnings(currency: '\$', value: 51)),
  'besahy': Creator(account: 'besahy', patrons: 50, earnings: null),
  'bihusinfo': Creator(account: 'bihusinfo', patrons: 675, earnings: Earnings(currency: '\$', value: 3568)),
  'BlogerFM': Creator(account: 'BlogerFM', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'blogmayster': Creator(account: 'blogmayster', patrons: 41, earnings: Earnings(currency: '\$', value: 160)),
  'Bykvu': Creator(account: 'Bykvu', patrons: null, earnings: null),
  'chaplinskyvlog': Creator(account: 'chaplinskyvlog', patrons: null, earnings: null),
  'chtyvo': Creator(account: 'chtyvo', patrons: 17, earnings: null),
  'chytomo': Creator(account: 'chytomo', patrons: 105, earnings: Earnings(currency: '\$', value: 560)),
  'cikavaideya': Creator(account: 'cikavaideya', patrons: null, earnings: null),
  'CikavaNauka': Creator(account: 'CikavaNauka', patrons: 292, earnings: Earnings(currency: '\$', value: 1338)),
  'costua': Creator(account: 'costua', patrons: 146, earnings: Earnings(currency: '\$', value: 555)),
  'cukr': Creator(account: 'cukr', patrons: 39, earnings: Earnings(currency: '\$', value: 218)),
  'diasporiana': Creator(account: 'diasporiana', patrons: null, earnings: Earnings(currency: '\$', value: 94)),
  'Did_Oles_Falcon_UA': Creator(account: 'Did_Oles_Falcon_UA', patrons: 42, earnings: null),
  'DITHOM': Creator(account: 'DITHOM', patrons: null, earnings: Earnings(currency: '\$', value: 28)),
  'diypodcast': Creator(account: 'diypodcast', patrons: null, earnings: null),
  'dolliteraturne': Creator(account: 'dolliteraturne', patrons: null, earnings: null),
  'donorua': Creator(account: 'donorua', patrons: 69, earnings: Earnings(currency: '\$', value: 313)),
  'dostupno2020': Creator(account: 'dostupno2020', patrons: 12, earnings: Earnings(currency: '\$', value: 76)),
  'dovkolabotanika': Creator(account: 'dovkolabotanika', patrons: 77, earnings: Earnings(currency: '\$', value: 255)),
  'dustanciyka': Creator(account: 'dustanciyka', patrons: 24, earnings: Earnings(currency: '\$', value: 41)),
  'dvokolisni_hroniky': Creator(account: 'dvokolisni_hroniky', patrons: 84, earnings: Earnings(currency: '\$', value: 453)),
  'eileena': Creator(account: 'eileena', patrons: 216, earnings: null),
  'enjoythescience': Creator(account: 'enjoythescience', patrons: null, earnings: null),
  'enma_and_books': Creator(account: 'enma_and_books', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'EuropeanPravda': Creator(account: 'EuropeanPravda', patrons: 132, earnings: Earnings(currency: '\$', value: 859)),
  'faideyren': Creator(account: 'faideyren', patrons: null, earnings: null),
  'familybudgetcomua': Creator(account: 'familybudgetcomua', patrons: 69, earnings: null),
  'fazugenealogy': Creator(account: 'fazugenealogy', patrons: null, earnings: null),
  'findwayua': Creator(account: 'findwayua', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'fromfaraway': Creator(account: 'fromfaraway', patrons: 0, earnings: Earnings(currency: '', value: 0)),
  'fvua': Creator(account: 'fvua', patrons: 310, earnings: null),
  'gamestreetua': Creator(account: 'gamestreetua', patrons: 11, earnings: Earnings(currency: '\$', value: 9)),
  'Geek_Informator': Creator(account: 'Geek_Informator', patrons: null, earnings: null),
  'Geek_Journal': Creator(account: 'Geek_Journal', patrons: 938, earnings: null),
  'GulbanuBibicheva': Creator(account: 'GulbanuBibicheva', patrons: null, earnings: null),
  'gwean_maslinka': Creator(account: 'gwean_maslinka', patrons: 199, earnings: Earnings(currency: '\$', value: 563)),
  'happypaw': Creator(account: 'happypaw', patrons: 3, earnings: Earnings(currency: '\$', value: 64)),
  'historyUA': Creator(account: 'historyUA', patrons: 790, earnings: Earnings(currency: '\$', value: 4153)),
  'historywall': Creator(account: 'historywall', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'horobyna': Creator(account: 'horobyna', patrons: 34, earnings: null),
  'hotperevod': Creator(account: 'hotperevod', patrons: 2, earnings: null),
  'Hromadske_Radio': Creator(account: 'Hromadske_Radio', patrons: 21, earnings: Earnings(currency: '\$', value: 140)),
  'imtgsh': Creator(account: 'imtgsh', patrons: 1100, earnings: null),
  'informnapalm': Creator(account: 'informnapalm', patrons: 231, earnings: null),
  'inforules': Creator(account: 'inforules', patrons: 22, earnings: Earnings(currency: '\$', value: 166)),
  'islndtv': Creator(account: 'islndtv', patrons: 2828, earnings: Earnings(currency: '\$', value: 4449)),
  'itguildukraine': Creator(account: 'itguildukraine', patrons: 270, earnings: Earnings(currency: '\$', value: 2997)),
  'itpassions': Creator(account: 'itpassions', patrons: null, earnings: null),
  'itworksonmypc': Creator(account: 'itworksonmypc', patrons: 182, earnings: Earnings(currency: '\$', value: 1180)),
  'iyura': Creator(account: 'iyura', patrons: null, earnings: Earnings(currency: '\$', value: 24)),
  'jarvis_net_ua': Creator(account: 'jarvis_net_ua', patrons: null, earnings: Earnings(currency: '\$', value: 10)),
  'JBPetersonUkraine': Creator(account: 'JBPetersonUkraine', patrons: null, earnings: null),
  'kartofanchyk': Creator(account: 'kartofanchyk', patrons: 1, earnings: Earnings(currency: '\$', value: 21)),
  'kgbfiles': Creator(account: 'kgbfiles', patrons: 40, earnings: Earnings(currency: '\$', value: 118)),
  'KhmarynkaUA': Creator(account: 'KhmarynkaUA', patrons: 183, earnings: null),
  'kliusmarichka': Creator(account: 'kliusmarichka', patrons: null, earnings: Earnings(currency: '\$', value: 6)),
  'knyzhkova_dylerka': Creator(account: 'knyzhkova_dylerka', patrons: null, earnings: Earnings(currency: '\$', value: 3)),
  'konotopcity': Creator(account: 'konotopcity', patrons: 4, earnings: Earnings(currency: '\$', value: 28)),
  'kozak_media': Creator(account: 'kozak_media', patrons: 18, earnings: Earnings(currency: '\$', value: 113)),
  'krutoznavstvo': Creator(account: 'krutoznavstvo', patrons: 0, earnings: null),
  'ksenia_kellerman': Creator(account: 'ksenia_kellerman', patrons: 51, earnings: Earnings(currency: '\$', value: 160)),
  'kultpodcast': Creator(account: 'kultpodcast', patrons: 111, earnings: Earnings(currency: '\$', value: 584)),
  'kuznetsovalife': Creator(account: 'kuznetsovalife', patrons: null, earnings: null),
  'les_kurbas_theatre': Creator(account: 'les_kurbas_theatre', patrons: 22, earnings: Earnings(currency: '\$', value: 160)),
  'letslearnukrainian': Creator(account: 'letslearnukrainian', patrons: null, earnings: Earnings(currency: '\$', value: 106)),
  'liganet': Creator(account: 'liganet', patrons: 192, earnings: Earnings(currency: '\$', value: 795)),
  'liroom': Creator(account: 'liroom', patrons: 18, earnings: Earnings(currency: '\$', value: 93)),
  'lowcostua': Creator(account: 'lowcostua', patrons: null, earnings: Earnings(currency: '\$', value: 3)),
  'loyer': Creator(account: 'loyer', patrons: 9, earnings: null),
  'lustrum': Creator(account: 'lustrum', patrons: null, earnings: Earnings(currency: '\$', value: 16)),
  'LvivNationalPhilharmonic': Creator(account: 'LvivNationalPhilharmonic', patrons: 3, earnings: null),
  'Lykhovii': Creator(account: 'Lykhovii', patrons: 96, earnings: Earnings(currency: '\$', value: 811)),
  'MaksPodzigun': Creator(account: 'MaksPodzigun', patrons: 745, earnings: null),
  'mangua': Creator(account: 'mangua', patrons: null, earnings: null),
  'manifestplatform': Creator(account: 'manifestplatform', patrons: 44, earnings: Earnings(currency: '\$', value: 104)),
  'mariamblog': Creator(account: 'mariamblog', patrons: 73, earnings: Earnings(currency: '\$', value: 271)),
  'mefreel': Creator(account: 'mefreel', patrons: 27, earnings: Earnings(currency: '\$', value: 65)),
  'merezhyvo': Creator(account: 'merezhyvo', patrons: 30, earnings: Earnings(currency: '\$', value: 121)),
  'miketvua': Creator(account: 'miketvua', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'milinua': Creator(account: 'milinua', patrons: 822, earnings: Earnings(currency: '\$', value: 2934)),
  'mokrec': Creator(account: 'mokrec', patrons: 222, earnings: Earnings(currency: '\$', value: 1648)),
  'mukha': Creator(account: 'mukha', patrons: 4, earnings: null),
  'musetang': Creator(account: 'musetang', patrons: 88, earnings: null),
  'nareshticlub': Creator(account: 'nareshticlub', patrons: 16, earnings: Earnings(currency: '\$', value: 78)),
  'naukaua': Creator(account: 'naukaua', patrons: 150, earnings: Earnings(currency: '\$', value: 665)),
  'nebolviv': Creator(account: 'nebolviv', patrons: null, earnings: Earnings(currency: '\$', value: 2)),
  'need_science': Creator(account: 'need_science', patrons: 9, earnings: null),
  'nestorvolya': Creator(account: 'nestorvolya', patrons: null, earnings: null),
  'nicopogarskiy': Creator(account: 'nicopogarskiy', patrons: 19, earnings: Earnings(currency: '\$', value: 32)),
  'ninaukraine': Creator(account: 'ninaukraine', patrons: 14, earnings: Earnings(currency: '\$', value: 2)),
  'nonamepodcast': Creator(account: 'nonamepodcast', patrons: null, earnings: null),
  'NowasteUkraine': Creator(account: 'NowasteUkraine', patrons: 66, earnings: Earnings(currency: '\$', value: 237)),
  'obrazpublicua': Creator(account: 'obrazpublicua', patrons: 19, earnings: null),
  'odesafineartsmuseum': Creator(account: 'odesafineartsmuseum', patrons: 14, earnings: Earnings(currency: '\$', value: 41)),
  'office_transformation': Creator(account: 'office_transformation', patrons: 543, earnings: Earnings(currency: '\$', value: 5475)),
  'oldboiua': Creator(account: 'oldboiua', patrons: 319, earnings: Earnings(currency: '\$', value: 1576)),
  'Ole_Sia': Creator(account: 'Ole_Sia', patrons: null, earnings: null),
  'oleksandr_ant': Creator(account: 'oleksandr_ant', patrons: 27, earnings: null),
  'olesyabobruyko': Creator(account: 'olesyabobruyko', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'omtvua': Creator(account: 'omtvua', patrons: 29, earnings: Earnings(currency: '\$', value: 106)),
  'otvinta': Creator(account: 'otvinta', patrons: null, earnings: Earnings(currency: '\$', value: 2)),
  'oum_spadshchyna': Creator(account: 'oum_spadshchyna', patrons: null, earnings: Earnings(currency: '\$', value: 14)),
  'pad0n': Creator(account: 'pad0n', patrons: 82, earnings: Earnings(currency: '\$', value: 417)),
  'palindrom': Creator(account: 'palindrom', patrons: 78, earnings: Earnings(currency: '\$', value: 600)),
  'PaniVchytelka': Creator(account: 'PaniVchytelka', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'pankarpan': Creator(account: 'pankarpan', patrons: 51, earnings: Earnings(currency: '\$', value: 122)),
  'pereozvuchka_ua': Creator(account: 'pereozvuchka_ua', patrons: 61, earnings: Earnings(currency: '\$', value: 134)),
  'pershosvit': Creator(account: 'pershosvit', patrons: null, earnings: null),
  'pityatko': Creator(account: 'pityatko', patrons: 92, earnings: Earnings(currency: '\$', value: 444)),
  'pivpodcast': Creator(account: 'pivpodcast', patrons: null, earnings: null),
  'portnikov': Creator(account: 'portnikov', patrons: 437, earnings: null),
  'ppidcast': Creator(account: 'ppidcast', patrons: 30, earnings: Earnings(currency: '\$', value: 109)),
  'prihodnik': Creator(account: 'prihodnik', patrons: 0, earnings: null),
  'propohody': Creator(account: 'propohody', patrons: 280, earnings: null),
  'prytula': Creator(account: 'prytula', patrons: 2007, earnings: Earnings(currency: '\$', value: 26140)),
  'PSUkraine': Creator(account: 'PSUkraine', patrons: null, earnings: null),
  'radioaristocrats': Creator(account: 'radioaristocrats', patrons: null, earnings: null),
  'radiopodil': Creator(account: 'radiopodil', patrons: 118, earnings: Earnings(currency: '\$', value: 598)),
  'radioskorbota': Creator(account: 'radioskorbota', patrons: 53, earnings: Earnings(currency: '\$', value: 82)),
  'radioskovoroda': Creator(account: 'radioskovoroda', patrons: 17, earnings: Earnings(currency: '\$', value: 26)),
  'raguli': Creator(account: 'raguli', patrons: 128, earnings: Earnings(currency: '\$', value: 550)),
  'rationalist': Creator(account: 'rationalist', patrons: 818, earnings: null),
  'readingmary': Creator(account: 'readingmary', patrons: 11, earnings: Earnings(currency: '\$', value: 11)),
  'rendarosua': Creator(account: 'rendarosua', patrons: 28, earnings: Earnings(currency: '\$', value: 159)),
  'rist_center': Creator(account: 'rist_center', patrons: null, earnings: null),
  'RockRadioUA': Creator(account: 'RockRadioUA', patrons: 30, earnings: null),
  'rsukraine_org_ua': Creator(account: 'rsukraine_org_ua', patrons: 41, earnings: Earnings(currency: '\$', value: 986)),
  'rudnyi': Creator(account: 'rudnyi', patrons: 3, earnings: Earnings(currency: '\$', value: 11)),
  'Salertino': Creator(account: 'Salertino', patrons: null, earnings: null),
  'sbt_localization': Creator(account: 'sbt_localization', patrons: 97, earnings: Earnings(currency: '\$', value: 641)),
  'serhiyzhadan': Creator(account: 'serhiyzhadan', patrons: 380, earnings: Earnings(currency: '\$', value: 4376)),
  'sershenzaritskaya': Creator(account: 'sershenzaritskaya', patrons: 495, earnings: null),
  'shitiknowlive': Creator(account: 'shitiknowlive', patrons: 470, earnings: null),
  'shobsho': Creator(account: 'shobsho', patrons: null, earnings: null),
  'skrypinua': Creator(account: 'skrypinua', patrons: 544, earnings: Earnings(currency: '\$', value: 2609)),
  'slidstvo_info': Creator(account: 'slidstvo_info', patrons: 119, earnings: Earnings(currency: '\$', value: 830)),
  'slukh': Creator(account: 'slukh', patrons: 100, earnings: Earnings(currency: '\$', value: 233)),
  'soblya': Creator(account: 'soblya', patrons: null, earnings: Earnings(currency: '\$', value: 3)),
  'stasmusicmaker': Creator(account: 'stasmusicmaker', patrons: null, earnings: Earnings(currency: '\$', value: 136)),
  'StopTheMoose': Creator(account: 'StopTheMoose', patrons: null, earnings: null),
  'strugachka': Creator(account: 'strugachka', patrons: 54, earnings: Earnings(currency: '\$', value: 189)),
  'svidomi': Creator(account: 'svidomi', patrons: 165, earnings: Earnings(currency: '\$', value: 1177)),
  'svitlana': Creator(account: 'svitlana', patrons: 4, earnings: null),
  'svitlotin': Creator(account: 'svitlotin', patrons: 17, earnings: Earnings(currency: '\$', value: 25)),
  'TA_studio': Creator(account: 'TA_studio', patrons: 68, earnings: Earnings(currency: '\$', value: 326)),
  'takflix': Creator(account: 'takflix', patrons: 282, earnings: Earnings(currency: '\$', value: 759)),
  'tanyacroft': Creator(account: 'tanyacroft', patrons: 22, earnings: null),
  'tatotake': Creator(account: 'tatotake', patrons: 911, earnings: null),
  'tatysho': Creator(account: 'tatysho', patrons: 1, earnings: Earnings(currency: '\$', value: 2)),
  'Tayemna_kimnata': Creator(account: 'Tayemna_kimnata', patrons: 12, earnings: null),
  'taytake': Creator(account: 'taytake', patrons: null, earnings: Earnings(currency: '\$', value: 19)),
  'techtoloka': Creator(account: 'techtoloka', patrons: 11, earnings: null),
  'teoriyagry': Creator(account: 'teoriyagry', patrons: null, earnings: Earnings(currency: '\$', value: 8)),
  'textyorgua': Creator(account: 'textyorgua', patrons: 199, earnings: Earnings(currency: '\$', value: 1250)),
  'thealphacentauri': Creator(account: 'thealphacentauri', patrons: 1094, earnings: null),
  'TheAsya': Creator(account: 'TheAsya', patrons: null, earnings: Earnings(currency: '\$', value: 5)),
  'tokar': Creator(account: 'tokar', patrons: 237, earnings: Earnings(currency: '\$', value: 949)),
  'torontotv': Creator(account: 'torontotv', patrons: 1370, earnings: Earnings(currency: '\$', value: 4384)),
  'totem_publisher': Creator(account: 'totem_publisher', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'UA_direct_democracy': Creator(account: 'UA_direct_democracy', patrons: 12, earnings: Earnings(currency: '\$', value: 4)),
  'uacomix': Creator(account: 'uacomix', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'uaestrada': Creator(account: 'uaestrada', patrons: 40, earnings: null),
  'uagenealogy': Creator(account: 'uagenealogy', patrons: null, earnings: null),
  'uanimals': Creator(account: 'uanimals', patrons: 389, earnings: null),
  'uareview': Creator(account: 'uareview', patrons: 50, earnings: Earnings(currency: '\$', value: 103)),
  'ubmdr': Creator(account: 'ubmdr', patrons: null, earnings: Earnings(currency: '\$', value: 39)),
  'ukrainedancing': Creator(account: 'ukrainedancing', patrons: null, earnings: null),
  'ukrainer': Creator(account: 'ukrainer', patrons: 395, earnings: Earnings(currency: '\$', value: 888)),
  'UkrainianLiveClassic': Creator(account: 'UkrainianLiveClassic', patrons: 124, earnings: null),
  'ukrainianweek': Creator(account: 'ukrainianweek', patrons: 51, earnings: Earnings(currency: '\$', value: 205)),
  'ukrmod': Creator(account: 'ukrmod', patrons: 74, earnings: null),
  'undergroundhumanities': Creator(account: 'undergroundhumanities', patrons: null, earnings: null),
  'user?u=16774315': Creator(account: 'user?u=16774315', patrons: null, earnings: null),
  'user?u=28899940': Creator(account: 'user?u=28899940', patrons: null, earnings: null),
  'user?u=44661751': Creator(account: 'user?u=44661751', patrons: null, earnings: null),
  'user?u=50286152': Creator(account: 'user?u=50286152', patrons: 149, earnings: Earnings(currency: '\$', value: 1322)),
  'user?u=76475135': Creator(account: 'user?u=76475135', patrons: null, earnings: null),
  'user?u=83097324': Creator(account: 'user?u=83097324', patrons: 35, earnings: Earnings(currency: '\$', value: 62)),
  'valerii': Creator(account: 'valerii', patrons: 324, earnings: Earnings(currency: '\$', value: 1715)),
  'vatashow': Creator(account: 'vatashow', patrons: 207, earnings: null),
  'vatatv': Creator(account: 'vatatv', patrons: 400, earnings: null),
  'vertigoUA': Creator(account: 'vertigoUA', patrons: 37, earnings: null),
  'verumT': Creator(account: 'verumT', patrons: 4, earnings: null),
  'vidminniotsinky': Creator(account: 'vidminniotsinky', patrons: null, earnings: null),
  'vmistozher': Creator(account: 'vmistozher', patrons: 69, earnings: Earnings(currency: '\$', value: 171)),
  'volynonline': Creator(account: 'volynonline', patrons: 2, earnings: Earnings(currency: '\$', value: 5)),
  'VorobieiBohdan': Creator(account: 'VorobieiBohdan', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'vovazilvova': Creator(account: 'vovazilvova', patrons: 24, earnings: Earnings(currency: '\$', value: 276)),
  'vovkst': Creator(account: 'vovkst', patrons: null, earnings: null),
  'vrajennya': Creator(account: 'vrajennya', patrons: 92, earnings: null),
  'vsesvit_ua': Creator(account: 'vsesvit_ua', patrons: 23, earnings: Earnings(currency: '\$', value: 90)),
  'vyshnevyjcvit': Creator(account: 'vyshnevyjcvit', patrons: 15, earnings: Earnings(currency: '\$', value: 22)),
  'WBG': Creator(account: 'WBG', patrons: 25, earnings: null),
  'wildfoxfilm': Creator(account: 'wildfoxfilm', patrons: 49, earnings: Earnings(currency: '\$', value: 283)),
  'wszystko_band': Creator(account: 'wszystko_band', patrons: 6, earnings: null),
  'yanareadwithme': Creator(account: 'yanareadwithme', patrons: null, earnings: Earnings(currency: '\$', value: 4)),
  'yanina': Creator(account: 'yanina', patrons: 494, earnings: Earnings(currency: '\$', value: 3025)),
  'zagin': Creator(account: 'zagin', patrons: 421, earnings: Earnings(currency: '\$', value: 740)),
  'zasnovnyky': Creator(account: 'zasnovnyky', patrons: null, earnings: null),
  'zhadanisobaki': Creator(account: 'zhadanisobaki', patrons: 61, earnings: Earnings(currency: '\$', value: 89)),
  'zhyteli_kyieva': Creator(account: 'zhyteli_kyieva', patrons: 2, earnings: Earnings(currency: '\$', value: 9)),
  'zvedeno': Creator(account: 'zvedeno', patrons: 17, earnings: Earnings(currency: '\$', value: 52)),
};
