final Map<String, String> data_name = {
  '23daphnia': 'Alla Komarova',
  '5HT': 'Namdak Tonpa',
  'AdrianZP': 'AdrianZP',
  'allyourhtml': 'Yuri Artiukh',
  'amanogawa': 'Спільнота Аманоґава',
  'animeK': 'Аніме Культура',
  'anitubeinua': 'AniTube',
  'AniUA': 'Studio AniUA',
  'asambleyA': 'Таємна АсамблейА',
  'ATR_UA': 'Телеканал ATR',
  'autogeek': 'autogeek',
  'balytska': 'Balytska Vlog',
  'bazilikmedia': 'Bazilik Media',
  'bbproject': 'B&B project',
  'behindthenews': 'Behind the news',
  'belkininovak': 'Бєлкін та Новак Wrestling Куй ТБ',
  'bellatrixaiden': 'Bellatrix Aiden',
  'berehtyIF': 'ФранківськЯкийТребаБерегти',
  'besahy': 'Наші бесаги',
  'bihusinfo': 'Bihus.Info',
  'BlogerFM': 'BlogerFM',
  'blogmayster': 'Blogmayster',
  'Bykvu': 'Bykvu',
  'chaplinskyvlog': 'yulian chaplinskyi',
  'chtyvo': 'Чтиво',
  'chytomo': 'Читомо',
  'cikavaideya': 'Цікава Ідея',
  'CikavaNauka': 'Цікава наука',
  'costua': 'Ціна держави',
  'cukr': 'Цукр',
  'diasporiana': 'Олег Богуславський',
  'Did_Oles_Falcon_UA': 'Дід Олесь',
  'DITHOM': 'Dithom',
  'diypodcast': 'Дій. Подкаст про бізнес',
  'donorua': 'DonorUA',
  'dostupno2020': 'Dostupno.UA',
  'dovkolabotanika': 'Dovkolabotanika',
  'dustanciyka': 'DиSтанційка',
  'dvokolisni_hroniky': 'Двоколісні хроніки',
  'eileena': 'Eileen',
  'enjoythescience': 'Enjoy The Science',
  'enma_and_books': 'EnMaandBooks',
  'EuropeanPravda': 'European Pravda / Європейська правда',
  'faideyren': 'Faid Eyren',
  'familybudgetcomua': 'Сімейний Бюджет',
  'fazugenealogy': 'Sergii Fazulyanov',
  'findwayua': '#findway',
  'fromfaraway': 'From Far Away',
  'fvua': 'FanVoxUA - аніме та мультсеріали українською',
  'gamestreetua': 'GameStreetUA',
  'Geek_Informator': 'Geek Informator',
  'Geek_Journal': 'Geek Journal',
  'GulbanuBibicheva': 'Gulbanu Bibicheva',
  'gwean_maslinka': 'Gwean and Maslinka',
  'happypaw': 'Happy Paw',
  'historyUA': 'Історія Без Міфів',
  'historywall': 'History Wall',
  'horobyna': 'Горобина',
  'hotperevod': 'Хот Перевод',
  'Hromadske_Radio': 'Громадське радіо',
  'imtgsh': 'імені Т.Г. Шевченка',
  'informnapalm': 'International Volunteer Community InformNapalm',
  'inforules': 'Як не стати овочем',
  'islndtv': 'Islnd TV',
  'itguildukraine': 'IT Guild Ukraine',
  'itpassions': 'IT - Пристрасті',
  'itworksonmypc': 'Dima Maleev',
  'iyura': 'Yuri Vlasyuk',
  'jarvis_net_ua': 'Андрій та Анастасія Ільківи',
  'JBPetersonUkraine': 'Джордан Пітерсон українською',
  'kartofanchyk': 'Картофанчик',
  'kgbfiles': 'KGB files in Telegram',
  'KhmarynkaUA': 'Хмаринка',
  'kliusmarichka': 'Клюс Марічка',
  'knyzhkova_dylerka': 'Книжкова дилерка',
  'konotopcity': 'Конотоп.City',
  'kozak_media': 'Kozak Media',
  'krutoznavstvo': 'Крутознавство',
  'kultpodcast': 'Kult: Podcast',
  'kuznetsovalife': 'Eugenia Kuznetsova',
  'les_kurbas_theatre': 'Les Kurbas Theatre',
  'letslearnukrainian': 'Let\'s Learn Ukrainian',
  'liganet': 'Liga.net',
  'liroom': 'LiRoom',
  'lowcostua': 'Lowcost UA',
  'loyer': 'Lойер',
  'lustrum': 'Lustrum: все можна зрозуміти',
  'LvivNationalPhilharmonic': 'Lviv National Philharmonic of Ukraine',
  'Lykhovii': 'Novynarnia / Dmytro Lykhovii',
  'MaksPodzigun': 'Макс Подзігун',
  'mangua': 'MangUA',
  'manifestplatform': 'Спільнота «Маніфест»',
  'mariamblog': 'MariAm Blog',
  'mefreel': 'Freel',
  'merezhyvo': 'Дерев\'яне мереживо Чернігова',
  'miketvua': 'MikeTVUA',
  'milinua': 'mil.in.ua',
  'mokrec': 'MokRec',
  'mukha': 'Mukha',
  'musetang': 'Musetang',
  'nareshticlub': 'Нарешті',
  'naukaua': 'Nauka.ua',
  'nebolviv': 'nebo.lviv.ua',
  'need_science': 'Need / science & education',
  'nestorvolya': 'Нестор Воля',
  'nicopogarskiy': 'Papercraft by Nico Pogarskiy',
  'ninaukraine': 'Ніна-Україна',
  'nonamepodcast': 'No Name Podcast',
  'NowasteUkraine': 'NoWaste Ukraine',
  'obrazpublicua': 'Obraz UA',
  'odesafineartsmuseum': 'OFAM | Odesa Fine Arts Museum ',
  'office_transformation': 'Офіс Трансформації',
  'oldboiua': 'Oldboi',
  'oleksandr_ant': 'Oleksandr Ant',
  'olesyabobruyko': 'Олеся Бобруйко',
  'omtvua': 'OmTV UA',
  'otvinta': 'Ot vinta',
  'oum_spadshchyna': 'Організація української молоді "Спадщина"',
  'pad0n': 'Падон',
  'palindrom': 'Паліндром',
  'PaniVchytelka': 'Катерина Лепська',
  'pankarpan': 'Пан Карпан',
  'pereozvuchka_ua': 'Переозвучка UA',
  'pershosvit': 'Першосвіт',
  'pityatko': 'Пітятко',
  'pivpodcast': 'Послухали і всьо',
  'portnikov': 'Vitaly Portnikov',
  'ppidcast': 'Подкаст Підкаст',
  'prihodnik': 'Пригодник',
  'propohody': 'ПроПоходи',
  'prytula': 'Сергій Притула',
  'PSUkraine': 'Play State Ukraine',
  'radioaristocrats': 'Radio Aristocrats',
  'radiopodil': 'Радіо Поділ',
  'radioskorbota': 'Радіо Скорбота',
  'radioskovoroda': 'Radio Skovoroda',
  'raguli': 'Ragulivna',
  'rationalist': 'Клятий раціоналіст',
  'rendarosua': 'Rendaros UA',
  'rist_center': 'Rist',
  'RockRadioUA': 'РокРадіо UA',
  'rsukraine_org_ua': 'Revived Soldiers Ukraine',
  'rudnyi': 'Maksym Rudnyi',
  'Salertino': 'Stepan',
  'sbt_localization': 'Sbt Localization',
  'serhiyzhadan': 'Сергій Жадан',
  'sershenzaritskaya': 'Sershen&Zaritskaya',
  'shitiknowlive': 'Шит ай ноу Лайв',
  'shobsho': 'ShobSho',
  'skrypinua': 'Skrypin.ua',
  'slidstvo_info': 'Слідство.Інфо',
  'slukh': 'Слух',
  'soblya': 'Сімейні обставини',
  'stasmusicmaker': 'Стас М\'юзикмейкер',
  'sternenko': 'Sternenko',
  'StopTheMoose': 'ЗупиниЛося',
  'strugachka': 'Струґачка',
  'svidomi': 'Свідомі',
  'svitlana': 'Svitlana',
  'svitlotin': 'Світлотінь',
  'TA_studio': 'TA',
  'takflix': 'Takflix',
  'tanyacroft': 'Tanya Croft',
  'tatotake': 'ТаТоТаке',
  'tatysho': 'Та ти шо?',
  'Tayemna_kimnata': 'Таємна кімната',
  'taytake': 'та й таке...',
  'techtoloka': 'Tech Toloka',
  'teoriyagry': 'Теорія Гри',
  'textyorgua': 'Texty.org.ua',
  'thealphacentauri': 'Alpha Centauri — Альфа Центавра',
  'TheAsya': 'Asya',
  'tokar': 'Tokar.ua',
  'torontotv': 'Телебачення Торонто',
  'totem_publisher': 'Тотемне Видавництво',
  'UA_direct_democracy': '"ПероксиД" - Пряма Демократія',
  'uacomix': 'UA Comix',
  'uaestrada': 'Українська естрада',
  'uagenealogy': 'UAGenealogy',
  'uanimals': 'UAnimals',
  'uareview': 'UaReview',
  'ubmdr': 'UBMDR - Ukrainian bone marrow donor registry',
  'ukrainedancing': 'Ukraine Dancing // Україномовна клубна музика',
  'ukrainer': 'Ukraїner',
  'UkrainianLiveClassic': 'Ukrainian Live Classic',
  'ukrainianweek': 'Український тиждень',
  'ukrmod': 'Ukrainian Modernism',
  'undergroundhumanities': 'Твоя Підпільна Гуманітарка',
  'user?u=16774315': 'Iryna Krylo',
  'user?u=28899940': 'Nastya Melnychenko',
  'user?u=44661751': 'Хащі ',
  'user?u=50286152': 'Подкаст «Простими словами»',
  'valerii': 'Valerii Markus',
  'vatashow': 'Андрій Полтава Карпов Вата Шоу',
  'vatatv': 'Viktor Lytovchenko',
  'vertigoUA': 'Vertigo',
  'verumT': 'Verum†',
  'vidminniotsinky': 'Відмінні оцінки',
  'vmistozher': 'Вмістожер',
  'volynonline': 'Волинь Online',
  'VorobieiBohdan': 'Астроном-любитель',
  'vovazilvova': 'vovazilvova',
  'vovkst': 'Вовк з Шевченка стріт',
  'vrajennya': 'Враження UA',
  'vsesvit_ua': 'Всесвіт UA',
  'vyshnevyjcvit': 'Вишневий Цвіт',
  'WBG': 'Світ настільних ігор',
  'wildfoxfilm': 'Wild Fox Film',
  'wszystko_band': 'Wszystko_band',
  'yanina': 'Yanina Sokolova',
  'zagin': 'Zagin Kinomaniv',
  'zasnovnyky': 'Засновники',
  'zhadanisobaki': 'Жадан і Собаки',
  'zhyteli_kyieva': 'Zhyteli Kyieva',
  'zvedeno': 'Zvedeno',
};
