import 'creator.dart';

final Map<String, Creator> data = {
  '23daphnia': Creator(account: '23daphnia', patrons: 2, earnings: Earnings(currency: '\$', value: 21)),
  '5HT': Creator(account: '5HT', patrons: 6, earnings: Earnings(currency: '\$', value: 39)),
  'AdrianZP': Creator(account: 'AdrianZP', patrons: 107, earnings: Earnings(currency: '\$', value: 431)),
  'aiesechouseua': Creator(account: 'aiesechouseua', patrons: 45, earnings: null),
  'allyourhtml': Creator(account: 'allyourhtml', patrons: 176, earnings: Earnings(currency: '\$', value: 320)),
  'amanogawa': Creator(account: 'amanogawa', patrons: 21, earnings: Earnings(currency: '\$', value: 184)),
  'AngryUA': Creator(account: 'AngryUA', patrons: 2, earnings: Earnings(currency: '\$', value: 6)),
  'animeK': Creator(account: 'animeK', patrons: 3, earnings: Earnings(currency: '\$', value: 4)),
  'anitubeinua': Creator(account: 'anitubeinua', patrons: null, earnings: null),
  'AniUA': Creator(account: 'AniUA', patrons: 6, earnings: Earnings(currency: '\$', value: 14)),
  'annika_blog': Creator(account: 'annika_blog', patrons: 7, earnings: Earnings(currency: '\$', value: 30)),
  'asambleyA': Creator(account: 'asambleyA', patrons: 2, earnings: Earnings(currency: '\$', value: 10)),
  'ATR_UA': Creator(account: 'ATR_UA', patrons: 88, earnings: Earnings(currency: '\$', value: 661)),
  'autogeek': Creator(account: 'autogeek', patrons: 16, earnings: null),
  'balytska': Creator(account: 'balytska', patrons: 7, earnings: Earnings(currency: '\$', value: 15)),
  'bazilikmedia': Creator(account: 'bazilikmedia', patrons: 4, earnings: Earnings(currency: '\$', value: 14)),
  'bbproject': Creator(account: 'bbproject', patrons: 77, earnings: null),
  'beautyandgloom': Creator(account: 'beautyandgloom', patrons: 6, earnings: null),
  'behindthenews': Creator(account: 'behindthenews', patrons: 47, earnings: Earnings(currency: '\$', value: 232)),
  'belkininovak': Creator(account: 'belkininovak', patrons: 457, earnings: Earnings(currency: '\$', value: 571)),
  'bellatrixaiden': Creator(account: 'bellatrixaiden', patrons: 7, earnings: Earnings(currency: '\$', value: 23)),
  'berehtyIF': Creator(account: 'berehtyIF', patrons: 10, earnings: Earnings(currency: '\$', value: 51)),
  'besahy': Creator(account: 'besahy', patrons: 10, earnings: Earnings(currency: '\$', value: 56)),
  'bez_mezh_studios': Creator(account: 'bez_mezh_studios', patrons: 11, earnings: Earnings(currency: '\$', value: 153)),
  'bihusinfo': Creator(account: 'bihusinfo', patrons: 678, earnings: Earnings(currency: '\$', value: 5901)),
  'BlogerFM': Creator(account: 'BlogerFM', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'blogmayster': Creator(account: 'blogmayster', patrons: 41, earnings: Earnings(currency: '\$', value: 160)),
  'Bykvu': Creator(account: 'Bykvu', patrons: null, earnings: null),
  'chaplinskyvlog': Creator(account: 'chaplinskyvlog', patrons: null, earnings: null),
  'ChasIstoriy': Creator(account: 'ChasIstoriy', patrons: 5, earnings: Earnings(currency: '\$', value: 19)),
  'chtyvo': Creator(account: 'chtyvo', patrons: 17, earnings: null),
  'chytomo': Creator(account: 'chytomo', patrons: 16, earnings: Earnings(currency: '\$', value: 68)),
  'cikavaideya': Creator(account: 'cikavaideya', patrons: 92, earnings: Earnings(currency: '\$', value: 589)),
  'CikavaNauka': Creator(account: 'CikavaNauka', patrons: 292, earnings: Earnings(currency: '\$', value: 1338)),
  'comixua': Creator(account: 'comixua', patrons: 13, earnings: Earnings(currency: '\$', value: 153)),
  'costua': Creator(account: 'costua', patrons: 36, earnings: Earnings(currency: '€', value: 114)),
  'cukr': Creator(account: 'cukr', patrons: 39, earnings: Earnings(currency: '\$', value: 218)),
  'dailymetal_radiogarta': Creator(account: 'dailymetal_radiogarta', patrons: 4, earnings: Earnings(currency: '\$', value: 31)),
  'deadlinetalkshow': Creator(account: 'deadlinetalkshow', patrons: 5, earnings: Earnings(currency: '\$', value: 21)),
  'diasporiana': Creator(account: 'diasporiana', patrons: 19, earnings: Earnings(currency: '\$', value: 83)),
  'Did_Oles_Falcon_UA': Creator(account: 'Did_Oles_Falcon_UA', patrons: 42, earnings: null),
  'DITHOM': Creator(account: 'DITHOM', patrons: 9, earnings: Earnings(currency: '\$', value: 62)),
  'diypodcast': Creator(account: 'diypodcast', patrons: 5, earnings: Earnings(currency: '\$', value: 16)),
  'docult': Creator(account: 'docult', patrons: 11, earnings: Earnings(currency: '\$', value: 62)),
  'donorua': Creator(account: 'donorua', patrons: 69, earnings: Earnings(currency: '\$', value: 313)),
  'dostupno2020': Creator(account: 'dostupno2020', patrons: 12, earnings: Earnings(currency: '\$', value: 76)),
  'dovkolabotanika': Creator(account: 'dovkolabotanika', patrons: 77, earnings: Earnings(currency: '\$', value: 255)),
  'dustanciyka': Creator(account: 'dustanciyka', patrons: 10, earnings: Earnings(currency: '\$', value: 35)),
  'dvokolisni_hroniky': Creator(account: 'dvokolisni_hroniky', patrons: 84, earnings: Earnings(currency: '\$', value: 453)),
  'eileena': Creator(account: 'eileena', patrons: 216, earnings: null),
  'enjoythescience': Creator(account: 'enjoythescience', patrons: 17, earnings: Earnings(currency: '\$', value: 54)),
  'enma_and_books': Creator(account: 'enma_and_books', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'faideyren': Creator(account: 'faideyren', patrons: null, earnings: null),
  'familybudgetcomua': Creator(account: 'familybudgetcomua', patrons: 37, earnings: null),
  'fazugenealogy': Creator(account: 'fazugenealogy', patrons: 12, earnings: Earnings(currency: '\$', value: 48)),
  'findwayua': Creator(account: 'findwayua', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'fromfaraway': Creator(account: 'fromfaraway', patrons: 0, earnings: Earnings(currency: '', value: 0)),
  'fvua': Creator(account: 'fvua', patrons: 79, earnings: Earnings(currency: '\$', value: 451)),
  'gamer_fm': Creator(account: 'gamer_fm', patrons: 9, earnings: Earnings(currency: '\$', value: 38)),
  'gamestreetua': Creator(account: 'gamestreetua', patrons: 10, earnings: Earnings(currency: '\$', value: 46)),
  'Geek_Informator': Creator(account: 'Geek_Informator', patrons: 2, earnings: Earnings(currency: '\$', value: 2)),
  'Geek_Journal': Creator(account: 'Geek_Journal', patrons: 938, earnings: null),
  'GulbanuBibicheva': Creator(account: 'GulbanuBibicheva', patrons: 5, earnings: Earnings(currency: '\$', value: 11)),
  'gwean_maslinka': Creator(account: 'gwean_maslinka', patrons: 61, earnings: Earnings(currency: '\$', value: 316)),
  'happypaw': Creator(account: 'happypaw', patrons: 3, earnings: Earnings(currency: '\$', value: 64)),
  'heroyika': Creator(account: 'heroyika', patrons: 17, earnings: Earnings(currency: '\$', value: 136)),
  'historyUA': Creator(account: 'historyUA', patrons: 458, earnings: Earnings(currency: '\$', value: 2207)),
  'historywall': Creator(account: 'historywall', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'horobyna': Creator(account: 'horobyna', patrons: 34, earnings: null),
  'hotperevod': Creator(account: 'hotperevod', patrons: 2, earnings: null),
  'Hromadske_Radio': Creator(account: 'Hromadske_Radio', patrons: 21, earnings: Earnings(currency: '\$', value: 140)),
  'imtgsh': Creator(account: 'imtgsh', patrons: 1100, earnings: null),
  'informnapalm': Creator(account: 'informnapalm', patrons: 359, earnings: null),
  'inforules': Creator(account: 'inforules', patrons: 22, earnings: Earnings(currency: '\$', value: 166)),
  'inshe': Creator(account: 'inshe', patrons: 12, earnings: Earnings(currency: '€', value: 44)),
  'islndtv': Creator(account: 'islndtv', patrons: 69, earnings: Earnings(currency: '\$', value: 538)),
  'itguildukraine': Creator(account: 'itguildukraine', patrons: 270, earnings: Earnings(currency: '\$', value: 2997)),
  'itpassions': Creator(account: 'itpassions', patrons: 11, earnings: Earnings(currency: '\$', value: 89)),
  'itworksonmypc': Creator(account: 'itworksonmypc', patrons: 182, earnings: Earnings(currency: '\$', value: 1180)),
  'iyura': Creator(account: 'iyura', patrons: 6, earnings: Earnings(currency: '\$', value: 24)),
  'jarvis_net_ua': Creator(account: 'jarvis_net_ua', patrons: 15, earnings: Earnings(currency: '\$', value: 80)),
  'JBPetersonUkraine': Creator(account: 'JBPetersonUkraine', patrons: 28, earnings: Earnings(currency: '\$', value: 96)),
  'kartofanchyk': Creator(account: 'kartofanchyk', patrons: 1, earnings: Earnings(currency: '\$', value: 21)),
  'kgbfiles': Creator(account: 'kgbfiles', patrons: 40, earnings: Earnings(currency: '\$', value: 118)),
  'KhmarynkaUA': Creator(account: 'KhmarynkaUA', patrons: 3, earnings: Earnings(currency: '\$', value: 7)),
  'kinshov': Creator(account: 'kinshov', patrons: 2, earnings: Earnings(currency: '\$', value: 2)),
  'kliusmarichka': Creator(account: 'kliusmarichka', patrons: 3, earnings: Earnings(currency: '\$', value: 15)),
  'knyzhkova_dylerka': Creator(account: 'knyzhkova_dylerka', patrons: 10, earnings: Earnings(currency: '\$', value: 20)),
  'kolegistudio': Creator(account: 'kolegistudio', patrons: 305, earnings: Earnings(currency: '\$', value: 1298)),
  'konotopcity': Creator(account: 'konotopcity', patrons: 4, earnings: Earnings(currency: '\$', value: 28)),
  'kozak_media': Creator(account: 'kozak_media', patrons: 18, earnings: Earnings(currency: '\$', value: 113)),
  'krutoznavstvo': Creator(account: 'krutoznavstvo', patrons: 0, earnings: null),
  'kultpodcast': Creator(account: 'kultpodcast', patrons: 111, earnings: Earnings(currency: '\$', value: 584)),
  'kuznetsovalife': Creator(account: 'kuznetsovalife', patrons: null, earnings: null),
  'Lakuna': Creator(account: 'Lakuna', patrons: 2, earnings: Earnings(currency: '\$', value: 3)),
  'lee_online': Creator(account: 'lee_online', patrons: 10, earnings: null),
  'les_kurbas_theatre': Creator(account: 'les_kurbas_theatre', patrons: 24, earnings: Earnings(currency: '€', value: 345)),
  'liganet': Creator(account: 'liganet', patrons: 192, earnings: Earnings(currency: '\$', value: 795)),
  'liroom': Creator(account: 'liroom', patrons: 18, earnings: Earnings(currency: '\$', value: 93)),
  'liubovgoknyg': Creator(account: 'liubovgoknyg', patrons: 5, earnings: Earnings(currency: '€', value: 12)),
  'lowcostua': Creator(account: 'lowcostua', patrons: 9, earnings: Earnings(currency: '€', value: 21)),
  'loyer': Creator(account: 'loyer', patrons: 9, earnings: null),
  'lustrum': Creator(account: 'lustrum', patrons: 9, earnings: Earnings(currency: '€', value: 59)),
  'LvivNationalPhilharmonic': Creator(account: 'LvivNationalPhilharmonic', patrons: 3, earnings: null),
  'Lykhovii': Creator(account: 'Lykhovii', patrons: 92, earnings: Earnings(currency: '\$', value: 725)),
  'lyukmedia': Creator(account: 'lyukmedia', patrons: 23, earnings: Earnings(currency: '\$', value: 132)),
  'MaksPodzigun': Creator(account: 'MaksPodzigun', patrons: 745, earnings: null),
  'mangua': Creator(account: 'mangua', patrons: 27, earnings: Earnings(currency: '\$', value: 192)),
  'manifestplatform': Creator(account: 'manifestplatform', patrons: 66, earnings: Earnings(currency: '\$', value: 177)),
  'mariamblog': Creator(account: 'mariamblog', patrons: 73, earnings: Earnings(currency: '\$', value: 271)),
  'mefreel': Creator(account: 'mefreel', patrons: 26, earnings: Earnings(currency: '\$', value: 182)),
  'merezhyvo': Creator(account: 'merezhyvo', patrons: 16, earnings: Earnings(currency: '\$', value: 85)),
  'miketvua': Creator(account: 'miketvua', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'milinua': Creator(account: 'milinua', patrons: 161, earnings: Earnings(currency: '\$', value: 849)),
  'mokrec': Creator(account: 'mokrec', patrons: 222, earnings: Earnings(currency: '\$', value: 1648)),
  'mukha': Creator(account: 'mukha', patrons: 4, earnings: null),
  'musetang': Creator(account: 'musetang', patrons: 30, earnings: Earnings(currency: '\$', value: 88)),
  'nareshticlub': Creator(account: 'nareshticlub', patrons: 6, earnings: Earnings(currency: '\$', value: 44)),
  'naukaua': Creator(account: 'naukaua', patrons: 150, earnings: Earnings(currency: '\$', value: 665)),
  'nebolviv': Creator(account: 'nebolviv', patrons: 3, earnings: Earnings(currency: '\$', value: 11)),
  'need_science': Creator(account: 'need_science', patrons: 9, earnings: null),
  'neformat': Creator(account: 'neformat', patrons: 14, earnings: Earnings(currency: '\$', value: 44)),
  'nestorvolya': Creator(account: 'nestorvolya', patrons: null, earnings: null),
  'nicopogarskiy': Creator(account: 'nicopogarskiy', patrons: 19, earnings: Earnings(currency: '\$', value: 32)),
  'ninaukraine': Creator(account: 'ninaukraine', patrons: 6, earnings: Earnings(currency: '\$', value: 43)),
  'nonamepodcast': Creator(account: 'nonamepodcast', patrons: null, earnings: null),
  'NowasteUkraine': Creator(account: 'NowasteUkraine', patrons: 97, earnings: Earnings(currency: '\$', value: 834)),
  'obrazpublicua': Creator(account: 'obrazpublicua', patrons: 19, earnings: null),
  'odesafineartsmuseum': Creator(account: 'odesafineartsmuseum', patrons: 3, earnings: Earnings(currency: '\$', value: 19)),
  'office_transformation': Creator(account: 'office_transformation', patrons: 356, earnings: Earnings(currency: '\$', value: 4359)),
  'oldboiua': Creator(account: 'oldboiua', patrons: 319, earnings: Earnings(currency: '\$', value: 1576)),
  'oleksandr_ant': Creator(account: 'oleksandr_ant', patrons: 27, earnings: null),
  'olesyabobruyko': Creator(account: 'olesyabobruyko', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'omtvua': Creator(account: 'omtvua', patrons: 29, earnings: Earnings(currency: '\$', value: 106)),
  'otvinta': Creator(account: 'otvinta', patrons: 5, earnings: Earnings(currency: '\$', value: 18)),
  'oum_spadshchyna': Creator(account: 'oum_spadshchyna', patrons: 8, earnings: Earnings(currency: '\$', value: 18)),
  'pad0n': Creator(account: 'pad0n', patrons: 82, earnings: Earnings(currency: '\$', value: 417)),
  'palindrom': Creator(account: 'palindrom', patrons: 78, earnings: Earnings(currency: '\$', value: 600)),
  'PaniVchytelka': Creator(account: 'PaniVchytelka', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'pankarpan': Creator(account: 'pankarpan', patrons: 51, earnings: Earnings(currency: '\$', value: 122)),
  'paralel3': Creator(account: 'paralel3', patrons: 24, earnings: null),
  'pereozvuchka_ua': Creator(account: 'pereozvuchka_ua', patrons: 61, earnings: Earnings(currency: '\$', value: 134)),
  'pershosvit': Creator(account: 'pershosvit', patrons: 4, earnings: Earnings(currency: '\$', value: 12)),
  'Pingvins': Creator(account: 'Pingvins', patrons: 20, earnings: null),
  'pityatko': Creator(account: 'pityatko', patrons: 30, earnings: Earnings(currency: '\$', value: 95)),
  'pivpodcast': Creator(account: 'pivpodcast', patrons: 7, earnings: Earnings(currency: '\$', value: 42)),
  'PlayUA': Creator(account: 'PlayUA', patrons: 72, earnings: Earnings(currency: '\$', value: 254)),
  'portnikov': Creator(account: 'portnikov', patrons: 437, earnings: null),
  'ppidcast': Creator(account: 'ppidcast', patrons: 30, earnings: Earnings(currency: '\$', value: 109)),
  'prihodnik': Creator(account: 'prihodnik', patrons: 0, earnings: null),
  'propohody': Creator(account: 'propohody', patrons: 280, earnings: null),
  'prytula': Creator(account: 'prytula', patrons: 1260, earnings: Earnings(currency: '\$', value: 14271)),
  'PSUkraine': Creator(account: 'PSUkraine', patrons: 28, earnings: Earnings(currency: '\$', value: 93)),
  'radioaristocrats': Creator(account: 'radioaristocrats', patrons: 79, earnings: Earnings(currency: '\$', value: 457)),
  'radiopodil': Creator(account: 'radiopodil', patrons: 118, earnings: Earnings(currency: '\$', value: 598)),
  'radioskorbota': Creator(account: 'radioskorbota', patrons: 47, earnings: Earnings(currency: '\$', value: 174)),
  'radioskovoroda': Creator(account: 'radioskovoroda', patrons: 4, earnings: Earnings(currency: '\$', value: 18)),
  'raguli': Creator(account: 'raguli', patrons: 347, earnings: Earnings(currency: '\$', value: 1383)),
  'rationalist': Creator(account: 'rationalist', patrons: 753, earnings: Earnings(currency: '\$', value: 3343)),
  'razvelibardak': Creator(account: 'razvelibardak', patrons: 259, earnings: Earnings(currency: '\$', value: 1422)),
  'rendarosua': Creator(account: 'rendarosua', patrons: 28, earnings: Earnings(currency: '\$', value: 159)),
  'rist_center': Creator(account: 'rist_center', patrons: 5, earnings: Earnings(currency: '\$', value: 108)),
  'robmenus': Creator(account: 'robmenus', patrons: 2, earnings: Earnings(currency: '\$', value: 3)),
  'RockRadioUA': Creator(account: 'RockRadioUA', patrons: 30, earnings: null),
  'rsukraine_org_ua': Creator(account: 'rsukraine_org_ua', patrons: 41, earnings: Earnings(currency: '\$', value: 986)),
  'rudnyi': Creator(account: 'rudnyi', patrons: 3, earnings: Earnings(currency: '\$', value: 11)),
  'Salertino': Creator(account: 'Salertino', patrons: 4, earnings: Earnings(currency: '\$', value: 10)),
  'savelife_in_ua': Creator(account: 'savelife_in_ua', patrons: 391, earnings: Earnings(currency: '\$', value: 6539)),
  'sbt_localization': Creator(account: 'sbt_localization', patrons: 97, earnings: Earnings(currency: '\$', value: 641)),
  'serhiyzhadan': Creator(account: 'serhiyzhadan', patrons: 126, earnings: Earnings(currency: '\$', value: 1138)),
  'sershenzaritskaya': Creator(account: 'sershenzaritskaya', patrons: 495, earnings: null),
  'Shablyk': Creator(account: 'Shablyk', patrons: 113, earnings: Earnings(currency: '\$', value: 386)),
  'shitiknowlive': Creator(account: 'shitiknowlive', patrons: 470, earnings: null),
  'shobsho': Creator(account: 'shobsho', patrons: 2, earnings: Earnings(currency: '\$', value: 5)),
  'skrypinua': Creator(account: 'skrypinua', patrons: 574, earnings: Earnings(currency: '\$', value: 4468)),
  'slidstvo_info': Creator(account: 'slidstvo_info', patrons: 119, earnings: Earnings(currency: '\$', value: 830)),
  'slukh': Creator(account: 'slukh', patrons: 46, earnings: Earnings(currency: '\$', value: 266)),
  'soblya': Creator(account: 'soblya', patrons: 9, earnings: Earnings(currency: '\$', value: 30)),
  'sternenko': Creator(account: 'sternenko', patrons: 895, earnings: Earnings(currency: '\$', value: 4712)),
  'StopTheMoose': Creator(account: 'StopTheMoose', patrons: null, earnings: null),
  'strugachka': Creator(account: 'strugachka', patrons: 54, earnings: Earnings(currency: '\$', value: 189)),
  'svidomi': Creator(account: 'svidomi', patrons: 40, earnings: Earnings(currency: '\$', value: 187)),
  'svitlana': Creator(account: 'svitlana', patrons: 4, earnings: null),
  'svitlotin': Creator(account: 'svitlotin', patrons: 4, earnings: Earnings(currency: '\$', value: 7)),
  'TA_studio': Creator(account: 'TA_studio', patrons: 68, earnings: Earnings(currency: '\$', value: 326)),
  'tanyacroft': Creator(account: 'tanyacroft', patrons: 22, earnings: null),
  'tatotake': Creator(account: 'tatotake', patrons: 291, earnings: Earnings(currency: '€', value: 822)),
  'tatysho': Creator(account: 'tatysho', patrons: 1, earnings: Earnings(currency: '\$', value: 2)),
  'Tayemna_kimnata': Creator(account: 'Tayemna_kimnata', patrons: 7, earnings: Earnings(currency: '\$', value: 13)),
  'taytake': Creator(account: 'taytake', patrons: 28, earnings: Earnings(currency: '\$', value: 227)),
  'techtoloka': Creator(account: 'techtoloka', patrons: 11, earnings: null),
  'telegrafdesign': Creator(account: 'telegrafdesign', patrons: 112, earnings: Earnings(currency: '\$', value: 626)),
  'teoriyagry': Creator(account: 'teoriyagry', patrons: 15, earnings: Earnings(currency: '\$', value: 68)),
  'textyorgua': Creator(account: 'textyorgua', patrons: 199, earnings: Earnings(currency: '\$', value: 1250)),
  'thealphacentauri': Creator(account: 'thealphacentauri', patrons: 1094, earnings: null),
  'TheAsya': Creator(account: 'TheAsya', patrons: 5, earnings: Earnings(currency: '€', value: 22)),
  'tokar': Creator(account: 'tokar', patrons: 237, earnings: Earnings(currency: '\$', value: 949)),
  'torontotv': Creator(account: 'torontotv', patrons: 1892, earnings: Earnings(currency: '\$', value: 10069)),
  'totem_publisher': Creator(account: 'totem_publisher', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'UA_direct_democracy': Creator(account: 'UA_direct_democracy', patrons: 41, earnings: Earnings(currency: '\$', value: 129)),
  'uacomix': Creator(account: 'uacomix', patrons: 1, earnings: Earnings(currency: '\$', value: 1)),
  'uaestrada': Creator(account: 'uaestrada', patrons: 10, earnings: Earnings(currency: '\$', value: 27)),
  'uagenealogy': Creator(account: 'uagenealogy', patrons: 6, earnings: Earnings(currency: '\$', value: 28)),
  'uanimals': Creator(account: 'uanimals', patrons: 389, earnings: null),
  'uareview': Creator(account: 'uareview', patrons: 50, earnings: Earnings(currency: '\$', value: 103)),
  'ubmdr': Creator(account: 'ubmdr', patrons: 3, earnings: Earnings(currency: '\$', value: 17)),
  'ukrainedancing': Creator(account: 'ukrainedancing', patrons: 2, earnings: Earnings(currency: '\$', value: 12)),
  'ukrainer': Creator(account: 'ukrainer', patrons: 327, earnings: Earnings(currency: '\$', value: 1849)),
  'UkrainianLiveClassic': Creator(account: 'UkrainianLiveClassic', patrons: null, earnings: null),
  'ukrainianweek': Creator(account: 'ukrainianweek', patrons: 38, earnings: Earnings(currency: '\$', value: 196)),
  'ukrmod': Creator(account: 'ukrmod', patrons: 20, earnings: null),
  'undergroundhumanities': Creator(account: 'undergroundhumanities', patrons: 508, earnings: Earnings(currency: '\$', value: 2277)),
  'user?u=16774315': Creator(account: 'user?u=16774315', patrons: null, earnings: null),
  'user?u=28899940': Creator(account: 'user?u=28899940', patrons: 3, earnings: Earnings(currency: '\$', value: 17)),
  'user?u=44661751': Creator(account: 'user?u=44661751', patrons: 107, earnings: Earnings(currency: '\$', value: 448)),
  'user?u=50286152': Creator(account: 'user?u=50286152', patrons: 149, earnings: Earnings(currency: '\$', value: 1322)),
  'valerii': Creator(account: 'valerii', patrons: 246, earnings: Earnings(currency: '\$', value: 2084)),
  'vatashow': Creator(account: 'vatashow', patrons: 207, earnings: null),
  'vatatv': Creator(account: 'vatatv', patrons: 400, earnings: null),
  'vertigoUA': Creator(account: 'vertigoUA', patrons: 37, earnings: null),
  'verumT': Creator(account: 'verumT', patrons: 4, earnings: null),
  'vidminniotsinky': Creator(account: 'vidminniotsinky', patrons: null, earnings: null),
  'viewua': Creator(account: 'viewua', patrons: 21, earnings: Earnings(currency: '\$', value: 94)),
  'vlad_storyteller': Creator(account: 'vlad_storyteller', patrons: 24, earnings: Earnings(currency: '\$', value: 73)),
  'vmistozher': Creator(account: 'vmistozher', patrons: 46, earnings: Earnings(currency: '\$', value: 191)),
  'volyasovich': Creator(account: 'volyasovich', patrons: 4, earnings: Earnings(currency: '\$', value: 9)),
  'volynonline': Creator(account: 'volynonline', patrons: 2, earnings: Earnings(currency: '\$', value: 5)),
  'VorobieiBohdan': Creator(account: 'VorobieiBohdan', patrons: 0, earnings: Earnings(currency: '\$', value: 0)),
  'vovazilvova': Creator(account: 'vovazilvova', patrons: 32, earnings: Earnings(currency: '\$', value: 616)),
  'vrajennya': Creator(account: 'vrajennya', patrons: 92, earnings: null),
  'vsesvit_ua': Creator(account: 'vsesvit_ua', patrons: 23, earnings: Earnings(currency: '\$', value: 90)),
  'vsesvitua': Creator(account: 'vsesvitua', patrons: 15, earnings: Earnings(currency: '\$', value: 52)),
  'vyshnevyjcvit': Creator(account: 'vyshnevyjcvit', patrons: 22, earnings: Earnings(currency: '\$', value: 79)),
  'WBG': Creator(account: 'WBG', patrons: 35, earnings: Earnings(currency: '\$', value: 191)),
  'wild_theatre': Creator(account: 'wild_theatre', patrons: 41, earnings: Earnings(currency: '\$', value: 352)),
  'wildfoxfilm': Creator(account: 'wildfoxfilm', patrons: 49, earnings: Earnings(currency: '\$', value: 283)),
  'wszystko_band': Creator(account: 'wszystko_band', patrons: 6, earnings: null),
  'yanina': Creator(account: 'yanina', patrons: 494, earnings: Earnings(currency: '\$', value: 3025)),
  'zagin': Creator(account: 'zagin', patrons: 113, earnings: Earnings(currency: '\$', value: 318)),
  'zasnovnyky': Creator(account: 'zasnovnyky', patrons: 2, earnings: Earnings(currency: '\$', value: 18)),
  'zhadanisobaki': Creator(account: 'zhadanisobaki', patrons: 29, earnings: Earnings(currency: '\$', value: 196)),
  'zhyteli_kyieva': Creator(account: 'zhyteli_kyieva', patrons: 2, earnings: Earnings(currency: '\$', value: 9)),
  'zvedeno': Creator(account: 'zvedeno', patrons: 10, earnings: Earnings(currency: '\$', value: 26)),
};
